AUTH0_AUDIENCE = ''
AUTH0_DOMAIN = ''
AUTH0_SECRET = ''
AUTH0_KNOWN_JWKS = ''
DATABASE_URL = ''
DATABASE_USERNAME = ''
DATABASE_PASSWORD = ''
STRIPE_KEY = ''
STRIPE_SECRET = ''
STRIPE_PRODUCT_LITE = ''
STRIPE_PRODUCT_PRO = ''
