name: Deploy Development Server

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          export RUSTFLAGS="-A warnings"  # Disable treating warnings as errors
          cargo test --all-features

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --all

  deploy:
    needs: [test, formatting]
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to Shuttle
      - name: Shuttle Deploy
        uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JF9X2ER6PF2Y645890WDFJYC
          extra-args: --allow-dirty --debug
          secrets: |
            AUTH0_AUDIENCE = '${{ secrets.AUTH0_AUDIENCE }}'
            AUTH0_DOMAIN = '${{ secrets.AUTH0_DOMAIN }}'
            AUTH0_SECRET = '${{ secrets.AUTH0_SECRET }}'
            AUTH0_KNOWN_JWKS = '${{ secrets.AUTH0_KNOWN_JWKS }}'
            DATABASE_URL = '${{ secrets.DATABASE_URL }}'
            DATABASE_USERNAME = '${{ secrets.DATABASE_USERNAME }}'
            DATABASE_PASSWORD = '${{ secrets.DATABASE_PASSWORD }}'
            STRIPE_KEY = '${{ secrets.STRIPE_KEY }}'
            STRIPE_SECRET = '${{ secrets.STRIPE_SECRET }}'
            STRIPE_PRODUCT_LITE = '${{ secrets.STRIPE_PRODUCT_LITE }}'
            STRIPE_PRODUCT_PRO = '${{ secrets.STRIPE_PRODUCT_PRO }}'
            STRIPE_WEBHOOK_SECRET = '${{ secrets.STRIPE_WEBHOOK_SECRET}}'
